app/helpers/todos_helper.rb, test/helpers/todo_helpers_test.rb
I was reading through TodosHelper and noticed a few places where we weren't using the helpers Rails provides for thinks like model ids and routes, so I fixed those up. I also added some very rudimentary characterization tests along the way.
=> Use the Rails helpers in more places

Gemfile
Simple groups so that the packaging can split out dependencies appropriately
=> Add db bundler groups so they can be excluded with --without

Gemfile, doc/installation.md
With this change and @GregSutcliffe's previous work in #1764 and #1765, users should never need to edit their Gemfiles to install Tracks.
=> Place therubyracer in a gem group

Gemfile, Gemfile.lock
cache_digests was the precursor to the native "Russian doll caching" built into Rails 4
=> Remove cache_digests gem

Gemfile, Gemfile.lock, doc/CHANGELOG.md, doc/installation.md, doc/upgrading.md
Thin performs much better than WEBrick, and it's a drop-in replacement, requiring no operational or development changes.
=> Use Thin instead of WEBrick

.travis.yml, lib/tasks/continuous_integration.rake
This makes SQLite fully supported, at the cost of significantly longer CI build times.
=> CI test on both MySQL and SQLite

app/models/todo.rb, test/controllers/todos_controller_test.rb, test/models/todo_test.rb
Only activate successors which are not completed
=> do not activate already completed todos, fix #1778

lib/project_from_todo.rb, test/models/project_from_todo_test.rb
When creating a project out of an action, add the tags from the action as default tags for the project.
This fixes #1448.
=> retain tags from action when transforming into project

Gemfile, Gemfile.lock
Use newer version to fix problems with Firefox 35+.
`selenium-webdriver` older than 2.45 does not work with Firefox 35 and newer.
=> Update cucumber version

features/support/tracks_step_helper.rb
in 'Scenario: Deleting a todo will remove it from the calendar' there may be two menus if the test is run on the last day of the month.
Observed in this build: https://travis-ci.org/TracksApp/tracks/builds/56555704
=> Fix cucumber test: select first menu

app/controllers/todos_controller.rb, features/step_definitions/todo_create_steps.rb, features/step_definitions/web_steps.rb, features/tickler.feature
Fix #1727 by sorting the actions by "show_from" in the tickler.
=> Sort deferred actions by "show from" in tickler, #1727

features/step_definitions/web_steps.rb
We're using RSpec 3 expectations syntax, in which `.should` is deprecated. This was throwing a deprecation warning.
FYI @C-Otto -- this was introduced in #1805.
=> Convert a .should expectation to expect()

app/controllers/todos/todo_create_params_helper.rb, app/controllers/todos_controller.rb, app/views/recurring_todos/_edit_form.html.erb, app/views/todos/_edit_form.html.erb, lib/tracks/attribute_handler.rb, test/controllers/todos_controller_test.rb, test/models/attribute_handler_test.rb, test/models/todo_create_params_helper_test.rb
I don't see why 'None' is better than the empty string, and this fixes #440. If you prefer still having 'None', please tell me what the advantages are.
Fix #440
=> replace 'None' project by empty string

Gemfile
The sanitize code in Tracks uses merge to copy Sanitize configurations,
but this was only introduced in version 3.0.0.
=> Provide minimum version for sanitize gem.

app/assets/javascripts/tracks.js.erb, app/controllers/todos_controller.rb
Fix two issues already mentioned in pull request #1777. This should be added, as #1777 is imcomplete/buggy without. Also relevant for release of 2.3.
1) Drag-n-drop removes the dragged todo if adding the dependency fails.
2) Adding a dependency does not show any error message in the edit form.
Fixes #1754.
=> (2.3) Circular dependencies

app/controllers/todos_controller.rb, app/helpers/todos_helper.rb, app/views/todos/destroy.js.erb, app/views/todos/toggle_check.js.erb, features/edit_a_todo.feature
We need to have `@project`/`@context` for the corresponding partial views. This was not provided when editing an existing action.
Furthermore, the JavaScript now also removes and re-adds an action when the context was changed, so that it appears in the correct container.
Fixes #1836 and #1804
=> (2.3) Provide data needed for partial views

app/models/project.rb, test/models/project_test.rb
Currently, a project cannot be blocked if at least one completed action exists. This was introduced in
acab98d4c7f2237bcd9fc44cd5e93a39582fe588, and I assume this change was not intended.
=> Projects with completed actions may be blocked

app/assets/stylesheets/mobile.css.scss
Hi @mattr-,
I've tried your PR and I like it! I've just noticed that adding this commit you can better style the input fields in order to have a consistent left/right margin.
We could better organise the date select with flexbox, but I don't know if it's a problem to use it, even if only on mobile (http://caniuse.com/#feat=flexbox).
=> Use box-sizing: border-box to style mobile input

.gitignore, Gemfile, Gemfile.lock, app/assets/stylesheets/tracks.css.scss, app/controllers/todos_controller.rb, app/helpers/todos_helper.rb, app/models/attachment.rb, app/models/message_gateway.rb, app/models/todo.rb, app/models/user.rb, app/views/todos/_todo.html.erb, config/initializers/paperclip.rb, config/routes.rb, db/migrate/20150805144100_create_attachments.rb, db/schema.rb, test/controllers/message_gateway_test.rb, test/fixtures/attachments.yml, test/models/attachment_test.rb, test/models/todo_test.rb
This is a squashed PR for adding attachments to the Todo model. Currently only emails received by the MessageGateway are saved as attachments. As such, this is the start of implementing a much asked for feature to add attachements to todos.
=> Add attachments to Todo model using Paperclip

app/controllers/todos_controller.rb, app/helpers/stats_helper.rb, app/models/recurring_todos/abstract_recurrence_pattern.rb, app/models/recurring_todos/monthly_recurrence_pattern.rb, app/models/stats/totals.rb, app/views/layouts/application.html.erb, app/views/layouts/mobile.m.erb, app/views/preferences/_date_and_time.html.erb, config/application.rb, config/environments/test.rb, lib/todo_from_recurring_todo.rb, test/controllers/recurring_todos_controller_test.rb, test/controllers/stats_controller_test.rb, test/controllers/todos_controller_test.rb, test/fixtures/contexts.yml, test/fixtures/notes.yml, test/fixtures/projects.yml, test/fixtures/recurring_todos.yml, test/fixtures/tags.yml, test/fixtures/todos.yml, test/models/project_test.rb, test/models/recurring_todo_test.rb, test/models/recurring_todos/abstract_recurrence_pattern_test.rb, test/models/todo_create_params_helper_test.rb, test/models/todo_test.rb, test/models/user_test.rb, test/test_helper.rb
There were several problems:
* Time.now returns the systems time, not the users time
* fixtures do not translate dates from timezone to utc, but stores the
date verbatim
* calling a controller will set the timezone to the preference of the
current_user. So it could be changed while you do not realize this. I
fixed the failing test, but problems could be elsewhere
=> Fix failing tests for non-UTC timezones

Gemfile.lock, app/assets/stylesheets/mobile.css.scss, app/views/todos/edit.m.erb, app/views/todos/new.m.erb, app/views/todos/show.m.erb
Entering new todos is somewhat painful. This set of changes increases the usability of the new todo mobile UI by enlarging elements to make them easier to hit.
Here's a screenshot of what these changes look like on a phone:
=> Increase the usability of the new todo mobile view

Gemfile, doc/installation.md
This is a backport from master of #1764, #1765, and #1767
One of the aims of was to make it easier for me to package Tracks, and I'm currently packaging the 2.3 branch. So, having verified that the groups approach is acceptable (by getting it into master), here is the 2.3 backport. I've checked that bundle install still works and the versions are correct:
```
Installing sqlite3 1.3.10
Installing mysql2 0.3.16
```
=> Update Gemfile and install doc to use db groups

app/assets/javascripts/tracks.js.erb, app/views/contexts/update.js.erb, app/views/projects/update.js.erb, app/views/projects/update_project_name.js.erb, app/views/todos/create.js.erb, features/context_edit.feature, features/project_edit.feature, features/step_definitions/context_steps.rb, features/step_definitions/todo_steps.rb
When adding a new action in the project view, after changing the project's name we need to set a hidden field in the form so that the updated project is used for new actions.
The same holds for the context view, where we need to update another hidden field after changing a context's name.
This fixes #1789.
In addition, this fixes #1796 by updating the context in the visible part of the form after changing the context's name in the context view.
=> (2.3) Update project name and context name in 'new action' form

app/helpers/application_helper.rb, app/models/recurring_todos/monthly_recurrence_pattern.rb, test/models/recurring_todos/monthly_recurrence_pattern_test.rb
The test for monthly recurring actions confused the fields every_other2 and every_other3 in the database. This fixes #1847.
=> Fix description of monthly recurring tests

app/assets/stylesheets/print.css.scss, app/assets/stylesheets/tracks.css.scss, app/helpers/todos_helper.rb, app/views/projects/done.html.erb, app/views/projects/show.html.erb, app/views/recurring_todos/done.html.erb, app/views/recurring_todos/index.html.erb, app/views/stats/done.html.erb, app/views/todos/all_done.html.erb
The code triggering the "new note" form is connected to the CSS class 'add_note_link', which was used all over the place for links inside the headers of (div) containers.
Fix #1851
=> Do not open 'new note' form when clicking unrelated links

app/assets/javascripts/tracks_pages.js, app/helpers/todos_helper.rb, app/views/todos/_todo.html.erb, app/views/todos/_update_successful.js.erb, app/views/todos/create.js.erb, app/views/todos/destroy.js.erb, app/views/todos/remove_predecessor.js.erb, app/views/todos/toggle_check.js.erb
Sort containers in JavaScript, for example when updating an action or creating a new one. This fixes #256.
This only works after re-rendering the todo partials. Any idea how to enforce this once?
I found some more places where we need to sort, this should cover about everything (feel free to tell me if I missed anything).
The JavaScript code has a few problems, and I might be looking into that soon. It seems we often try to change the contents of some action's div using .html(), which effectively adds a div inside the new div (both sharing the same id). Using replaceWith() might be the way to go, instead.
=> Sort containers

app/controllers/integrations_controller.rb, app/views/integrations/google_gadget.erb, app/views/integrations/index.de.html.erb, app/views/integrations/index.en.html.erb, app/views/integrations/index.nl.html.erb, config/locales/cs.yml, config/locales/de.yml, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/he.yml, config/locales/nl.yml, config/locales/ru.yml, config/routes.rb
Google has discontinued the "Add any gadget by URL" Labs feature. Remove
the feature from the application.
Fixes #1843
=> Remove the Google Gadget Integration

app/controllers/projects_controller.rb
=> (2.3) remove context if name is not set in update form

app/controllers/application_controller.rb
This prevents attachments to be seen as something different than
html content. For example, message/rfc822 for email was being
replaced by application/html causing wrong application to be
started on the client.
=> remove old hack to set content type to application/html

app/assets/javascripts/tracks.js.erb, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/legacy.css.scss, app/views/layouts/application.html.erb
This allows Bootstrap changes to be made in almost total isolation. The only element with overlapping/shared styles will be `body`.
=> Namespace the legacy CSS

app/views/projects/index.rss.builder
The current link incorrectly points to the contexts page.
=> Fix link in projects RSS feed

lib/login_system.rb
Returning a hash with explicit keys isn't strictly necessary with the
access methods we're using to get the values for those keys out of the
hash. Return an empty hash instead, simplifying the code.
Also remove the early return statements within the conditional. Those
are also unneeded since this is the last expression that's run in the
method.
=> Simplify the return values when using basic auth

Gemfile, Gemfile.lock
This allows us to support MySQL 5.7.
Keep it locked at the 0.3.x version due to problems with other apps and
the 0.4.x versions.
=> Bump mysql2 to 0.3.20

app/controllers/todos_controller.rb, app/models/todo.rb, test/models/todo_test.rb
Move the activation code to the model, so that it also is used when converting an action into a project.
Fixes #1881
See #1887
=> Activate successors on predecessor destroy

app/assets/stylesheets/application.css.scss, app/assets/stylesheets/login.css.scss, app/assets/stylesheets/tracks-logo.css.scss, app/helpers/bootstrap_flash_helper.rb, app/views/layouts/login.html.erb, app/views/login/login.html.erb, features/step_definitions/login_steps.rb
Makes use of both bootstrap and a rendering of the Tracks logo to provide a bit better experience in term of brand identity as well as also supporting mobile better.
There are a few things left to do here before this gets merged, but I wanted to provide something for feedback, since this is a large departure from our previous login page:
=> Redesign the login page

app/assets/stylesheets/legacy.css.scss, app/assets/stylesheets/login.css.scss, app/assets/stylesheets/tracks.css.scss, app/views/shared/_footer.html.erb
Matches the style of the existing footer and makes the links move to the next line instead of wrapping if the viewport is too small for all of the footer to fit on one line.
Also moves the footer over to bootstrap styles
This makes the footer work for both the login screen and other pages that aren't fully bootstrapped yet. It also solves a design issue that is really nitpicky but was driving me nuts. :smiley:
=> Update the footer to be more responsive

app/controllers/projects_controller.rb, test/controllers/projects_controller_test.rb, test/fixtures/projects.yml
I don't understand what the `.load` is supposed to do.
We could also discuss to also sort the `review`, `stalled` and `blocked` lists.
I'd prefer to not sort the `review` list, as
- all of the projects need to be reviewed now/soon-ish
- the user might have defined an order based in priority
This fixes #1960
=> Sort current projects

lib/tracks/utils.rb, test/controllers/todos_controller_test.rb
This causes the links to be opened in a new window/tab.
Existing (rendered) notes are not affected by this.
Fixes #1747
=> add target="_blank" for generated links

Gemfile, Gemfile.lock
I add this manually too often, so let's get it in the Gemfile.
Rails recommends `byebug` but it's Ruby-2.2-only and I still often find myself working on 1.9.3. We can switch when we go to Rails 5.
=> Add pry for debugging

app/views/layouts/application.html.erb
Tracks uses this javascript method in the application layout called `relative_to_root` to get relative paths for a lot of Javascript functions. However, it includes the fully qualified protocol and domain for the tracks site in question. If you have Tracks proxied through SSL with nginx, then you get a non-secure URL which causes the Javascript to not work to fetch things like contexts or projects for autocomplete.
Instead of using the `root_url` helper that Rails provides that won't know about SSL, just use a normal forward slash instead, so that you still get a path that's relative to the root instead of a URL.
=> Don't include a protocol or domain for relative_to_root

.travis.yml, lib/tasks/continuous_integration.rake
This will speed up the overall CI execution time.
It's possible this will miss things, but if a database-specific bug is filed because it isn't captured in our unit tests, it's a bug in the tests.
Ideally this could be limited to model tests only, but things aren't that well separated.
=> On Travis, restrict Cucumber tests to MySQL builds

app/views/preferences/_date_and_time.html.erb
Fixes #1997
This should turn the 1.9.3 "lite" (i.e. SQLite) build green.
=> Avoid using %i, which requires Ruby 2.0

features/support/tracks_cucumber_settings.rb
This prevents UI elements from being hidden by the top navbar. See https://github.com/SeleniumHQ/selenium/issues/1202.
Not a fix to #1979, but heading in the right direction.
Before: 233 failures
After: 181 failures
=> Selenium: scroll elements to bottom instead of top

app/assets/javascripts/application.js, app/assets/javascripts/tracks_pages.js, app/helpers/application_helper.rb, app/views/layouts/application.html.erb, config/initializers/assets.rb
* Restore the `javascript_tag_for_i18n_datepicker` helper (and actually use it)
* Include the datepicker i18n JS in the asset precompilation list
Ref #1975
=> Include datepicker i18n only as needed

app/views/search/_show_results_collection.html.erb
Based on the style used in the projects index page.
Fixes #2003.
=> Fix spacing in search results heading

app/views/layouts/application.html.erb
Reverts TracksApp/tracks#1986.
Can probably be best fixed by using `root_path` but let's just go ahead and unbreak it first.
=> Revert "Don't include a protocol or domain for relative_to_root"

app/assets/javascripts/tracks.js.erb, app/views/search/index.html.erb
How is this?
I removed the JS to focus the cursor in favour of HTML5 autofocus. Should I add a fallback for when it is not supported? 
Browser support info: http://caniuse.com/#feat=autofocus
=> Convert search page to bootstrap

app/assets/stylesheets/application.scss
=> Load jquery-ui-rails CSS via "require" instead of "import"

features/calendar.feature, features/context_edit.feature, features/dependencies.feature, features/shared_add_new_todo.feature
```
cucumber features/calendar.feature:27 # Scenario: Clearing the due date of a todo will remove it from the calendar
cucumber features/calendar.feature:37 # Scenario: Marking a todo complete will remove it from the calendar
cucumber features/context_edit.feature:55 # Scenario: Editing the context of the last todo will remove the todo and show empty message
cucumber features/dependencies.feature:27 # Scenario: I can edit a todo to add the todo as a dependency to another
cucumber features/shared_add_new_todo.feature:256 # Scenario: Adding a dependency to a todo updates the successor
```
=> Mark a few failing features as WIP until UI redesign is more complete

Gemfile, Gemfile.lock
=> Remove activerecord-deprecated_finders

app/views/shared/_navbar.html.erb
Before:
```html
<a href="/recurring_todos?title=Manage+recurring+actions">Recurring todos</a>
```
After:
```html
<a title="Manage recurring actions" href="/recurring_todos">Recurring todos</a>
```
=> Fix navbar link title of "Recurring Todos"

Gemfile.lock
Our previous version - `1.0.7` - is not compatible with OS X El Capitan.
Upgrading to the latest version fixed this issue.
=> Update eventmachine to 1.2.0.1

config/initializers/i18n-config.rb
In most cases, translations don't supply `:few` even though the language
may support the construct. Instead of the app blowing up if the
translation for `:few` doesn't exist, fall back to `:other` instead.
=> Add a fallback to :other for i18n

Gemfile, Gemfile.lock
We'll git rid of 1.9.3 support with Rails 5 (#2031) but until that happens I'd like the tests to stay green.
=> Hold rubocop back to fix tests on 1.9.3

doc/installation.md
I don't love having pointers to specific third parties in the actual Tracks source, so this change moves all that to the wiki.
=> Move alternative installation options to the wiki

app/models/stats/projects.rb, test/controllers/stats_controller_test.rb
Sorting by running time without a reverse takes the shortest running
projects.
Fixes #2085
=> Fix the top 10 longest running projects list

config/environments/production.rb, config/site.yml.tmpl, doc/installation.md
This is needed when tracks is running behind a webserver with https.
=> Makes force_ssl configurable

script/cibuild
The `ci:lite` task is busted but the `test` task works just fine. Discovered this while testing a rubocop upgrade and ran `rake test` before committing.
=> Use `rake test` instead of `ci:lite`

script/console, script/docker-environment, script/server
The docker based development environment is great for abstracting away all the various system details (and hopefully makes things easier to get going on Windows) but unless you know all the various switches to toggle to work with docker, it can be a pain in the neck.
This pull request adds a few extra scripts to bring up a rails console or a rails server. It also adds a bit of functionality that was missing before to get `docker-compose` to publish the service ports so you could actually get to the server that you're running :smile:
=> Remove some friction when running in development

config/locales/de.yml
This fixes issue #1745 by shorten link text. The meaning of the text is still clear.
=> Fix german locale mobile Header; refs #1745

app/controllers/application_controller.rb, app/controllers/calendar_controller.rb, app/controllers/contexts_controller.rb, app/controllers/integrations_controller.rb, app/controllers/login_controller.rb, app/controllers/mailgun_controller.rb, app/controllers/notes_controller.rb, app/controllers/preferences_controller.rb, app/controllers/projects_controller.rb, app/controllers/recurring_todos_controller.rb, app/controllers/stats_controller.rb, app/controllers/todos_controller.rb, app/controllers/users_controller.rb, lib/login_system.rb
I've been decomposing #2084 in order to make the actual Rails upgrade easier, since 5.1 and 5.2 will be after 5.0. This splits out the various updates to the Rails API that are available to us in Rails 4.2 into it's own PR.
To be clear, these are all @dnrce's changes, I'm just splitting up how they're applyed to the code base.
=> Compatibility updates for newer versions of Rails

test/controllers/notes_controller_test.rb, test/controllers/todos_controller_test.rb, test/integration/recurring_todos_test.rb, test/models/user_test.rb, test/test_helper.rb
Ruby has moved away from test-unit in favor of minitest and so this starts doing the same. It also cleans up some whitespace and adds a more performant random string generation algorithm.
=> Update some testing practices to use more relevant methods

app/controllers/calendar_controller.rb, app/controllers/contexts_controller.rb, app/controllers/projects_controller.rb, app/controllers/todos/todo_create_params_helper.rb, app/controllers/todos_controller.rb, config/application.rb, lib/tracks/attribute_handler.rb, test/controllers/calendar_controller_test.rb, test/controllers/contexts_controller_test.rb, test/controllers/feedlist_controller_test.rb, test/controllers/integrations_controller_test.rb, test/controllers/login_controller_test.rb, test/controllers/mailgun_controller_test.rb, test/controllers/notes_controller_test.rb, test/controllers/preferences_controller_test.rb, test/controllers/projects_controller_test.rb, test/controllers/recurring_todos_controller_test.rb, test/controllers/search_controller_test.rb, test/controllers/stats_controller_test.rb, test/controllers/todos_controller_test.rb, test/controllers/users_controller_test.rb, test/integration/recurring_todos_test.rb, test/integration/stories_test.rb, test/integration/todo_xml_api_test.rb, test/integration/users_xml_api_test.rb, test/models/todo_create_params_helper_test.rb, test/test_helper.rb
This is part one of the prepwork for Rails 5.1 by removing all the deprecation warnings the test suite screams at us when the tests are running.
Huge shoutout to @dnrce for doing all of this in #2084. This is the last PR from that monster of a PR to split out.
Closes #2084
=> Remove all the deprecations seen in the tests

app/models/application_record.rb, app/models/attachment.rb, app/models/context.rb, app/models/dependency.rb, app/models/note.rb, app/models/preference.rb, app/models/project.rb, app/models/recurring_todo.rb, app/models/tag.rb, app/models/tagging.rb, app/models/todo.rb, app/models/user.rb
Rails 5 requires the use of this superclass for all database backed model objects now.
I, uh, forgot this before. :disappointed:
=> Convert to ApplicationRecord

app/helpers/todos_helper.rb, lib/staleness.rb
Not sure what's going on with Rails' autoloading here, so fix it the ruby way by using plain ol' `require`
Closes #2137
=> Fix the undefined reference to Staleness

config/initializers/new_framework_defaults.rb
These are pointed out when running the test suite and at least one of them blocks the Rails 5.2 upgrade.
=> Remove Rails 5.1 deprecations

Gemfile, Gemfile.lock, bin/bundle, bin/setup, bin/update, bin/yarn, config/application.rb, config/boot.rb, config/cable.yml, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/content_security_policy.rb, config/initializers/cookies_serializer.rb, config/initializers/new_framework_defaults_5_2.rb, config/puma.rb, config/storage.yml
After the framework bump in #2144, run `rails app:update` to pull in the new framework changes and defaults.
=> Update the app for Rails 5.2

Gemfile, Gemfile.lock
I dislike the way this gem covers up important parts of the UI.
=> Remove rack-dev-mark

Dockerfile
Ruby 2.3 has reached end of life and is no longer maintained. Bump to
using Ruby 2.4 so that we remain on a supported Ruby version.
=> Bump Ruby to 2.4

app/controllers/todos_controller.rb, app/models/todos/undone_todos_query.rb, test/fixtures/projects.yml, test/fixtures/taggings.yml, test/fixtures/todos.yml, test/models/todos/undone_todos_query_test.rb
Extracts an object from the TodosController that is all about querying todos and only tangentially related to serving requests. Also adds a bunch of data to the fixtures to support the new tests for the query object.
=> Refactor out an object for querying not done todos

app/controllers/calendar_controller.rb, app/controllers/contexts_controller.rb, app/controllers/notes_controller.rb, app/controllers/projects_controller.rb, app/controllers/todos_controller.rb, app/controllers/users_controller.rb
Adding the :root option to those XML APIs that return a response when no items are found. The ones returning only a single item should return an error response if the requested item was found, and therefore forcing the root element shouldn't be necessary there.
=> #2036: Change empty XML responses to have the correct base element

app/models/user.rb
Uses a better SQL query to pull a single object vs. pulling a full set and then iterating over it.
Closes #2091
=> Prefer find_by over detect

app/views/search/_index.html.erb, app/views/search/index.html.erb, app/views/todos/_new_todo_form.html.erb
This should set the autofocus to the new todo entry form (which already
was set for autofocus) rather than the search box
Fixes #2156
Related to #1139
=> Remove the autofocus from the search fields

Gemfile, Gemfile.lock, app/helpers/rendering_helper.rb, test/helpers/rendering_helper_test.rb
Upgrade sanitize. Replaces #2125.
Fixes the incorrect test that the `sanitize` upgrade exposed.
=> Upgrade sanitize.

config/locales/cs.yml, config/locales/de.yml, config/locales/en.yml, config/locales/es.yml, config/locales/fr.yml, config/locales/nl.yml
This was preventing the app from loading, weirdly.
The error I was getting (in all places where I've made changes) looked like this: ```
I18n::InvalidLocaleData: can not load translations from /Users/srbaker/Projects/TracksApp/tracks/config/locales/en.yml: #<Psych::SyntaxError: (/Users/srbaker/Projects/TracksApp/tracks/config/locales/en.yml): found unknown escape character while parsing a quoted scalar at line 585 column 31>```
I don't know why I'm getting this and others aren't: I suspect I'm on a newer `libyaml` that is more strict.
I've confirmed this with the YAML 1.2 spec, and a few other projects around the web, such as: https://github.com/stympy/faker/pull/1305
=> Single quotes don't need to be escaped here.

app/controllers/application_controller.rb
The variables aren't initialised properly when doing a simple PUT call to update the context. The change ensures that the variables exist to avoid the server error.
=> Fixed bug causing context change to hidden returning a server error

db/migrate/20190618202817_add_user_id_to_tag.rb
This fixes the tag migration at least in my MySQL environment. exec_query apparently returns the results in constant formats while execute doesn't:
* https://stackoverflow.com/questions/14824453/rails-raw-sql-example#comment82683569_14840547
* https://api.rubyonrails.org/classes/ActiveRecord/Result.html
I tested the change on MySQL, SQlite and PostgreSQL in my own environment.
=> #2295: Fix for the migration bug in MySQL

README.md, config/initializers/tracks.rb, doc/CHANGELOG.md, doc/installation.md, doc/upgrading.md
I suggest we publish a new version 2.4.1 right away to avoid any users getting hit by the migration bug.
=> Version 2.4.1

app/assets/stylesheets/legacy.scss, app/views/shared/_add_new_item_form.html.erb, app/views/todos/_new_multi_todo_form.html.erb, app/views/todos/_new_todo_form.html.erb
This PR restyles the new todo forms to provide more space for the text boxes and the UI overall.
Before:
After:
This does make the forms take up more space but this looks way better.
=> Restyle the new todo forms

app/controllers/todos_controller.rb, app/helpers/todos_helper.rb, app/views/todos/destroy.js.erb
Project uses properties of `@original_item` over a number of similar-named variables (eg. `@original_item_description`, `@original_item_was_pending`, etc.)
Have left in `@original_item_due_date` and `@original_completed_period` as these are more complex, and not simply properties of the todo item.
----
Tests pass, and playing around with todo items suggests that everything continues to work normally with this refactor in place.
=> #2220: Use @original_item over other @original_item like instance variables

doc/installation.md
A very small update to the installation instructions, to point out that Ruby 2.7 is not tested.
I'm adding it, because in the way it's written at the moment "Tracks requires Ruby 2.4 or greater.", one can assume (as did I), that _all_versions greater than Ruby 2.4 are supported, and there seem to be some issues with 2.7.
=> Modified installation instructions, to note that Ruby 2.7 is not tested.

test/models/recurring_todo_test.rb
Now we're in 2020, some of the tests in `recurring_todo_test.rb#test_start_from_in_future` are no longer situated in the future.
I've updated the monthly recurring todos so that their start dates will always be in the future, and confirmed that these tests pass.
The "Every weekday" tests still seem to be passing, even though they're now starting in the past. Not sure what's up with that: perhaps I haven't properly grokked the recurring due date logic fully, or perhaps that's something weird in the logic.
=> Fix test_start_from_in_future

config/initializers/sanitizer.rb
Another tiny quality-of-life improvement.
From Loofah 2.3.0, `Loofah::HTML5::WhiteList` is deprecated in favour of `Loofah::HTML5::SafeList`. This commit checks to see if `Loofah::HTML5::SafeList` exists, and uses it when it can.
=> Use Loofah::HTML5::SafeList where possible

Gemfile, Gemfile.lock
This allows developers to take advantage of the better information you can get from editors that will integrate with this gem and the language server protocol.
=> Add solargraph as a developpment dependency

Dockerfile
What it says on the tin. Newer versions of Rails require newer versions of Ruby. Let's upgrade.
=> Update the base image for docker to ruby 2.6

db/migrate/20200109231555_change_todo_description.rb, db/schema.rb
DB field "todos.description" was type string, which
defaults to length 255 in MySQL. Model allows field
to be up to 300 characters, which could cause a DB
error, if user saved a description of between 255
and 300 characters.
Fixes #2274
=> Change "todos.description" from "string" to "text"

app/assets/javascripts/tracks.js.erb
Found this while working through some of the frontend code troubleshooting another bug. We don't support IE7 or IE8 anymore.
=> Remove support for IE7 and IE8

app/controllers/login_controller.rb
This should finally fix the exception seen when the app checks session expire time.
=> Use the right format for expiry_time

app/views/shared/_footer.html.erb
The "Contribute" link in the footer returns a 404, so have changed to the most relevant looking page.
Also changed all http links to https after confirming they have valid https endpoints.
Note that I haven't run the rake tests because Ive just changed a couple of links (and haven't yet got everything up and running locally).  do let me know if I need to do this!
=> Fix contribute link in footer and prefer HTTPS

app/assets/stylesheets/include/legacy.scss
This probably shouldn't be necessary, but I couldn't quickly figure out what had changed for the dialog to behave incorrectly. Seems to work.
Fixes #2468.
=> #2468: Fix the recurring todo dialog UI bug.

config/application.rb, config/site.yml.tmpl
When the application is exposed via proxy, i.e. client visible host
(e.g. example.org:443) is different than Ruby server (e.g.
localhost:3000), autocompletion does not work since the generated URLs
refer to the internal hostname.
The AJAX is constructed with root_url and that can be modified with
default_url_options. So the simple fix just allows specifying customized
default_url_options.
Fixes: #1416
=> Allow autocompletion behind proxy

Dockerfile
Pin Bundler to 2.4.22 so that 2.7 CI keeps working.
=> Install older version of Bundler in CI for Ruby 2.7

Dockerfile
=> Don't require the .git directory to exist for a successful Docker build.

Gemfile, Gemfile.lock, bin/rake, config/application.rb, config/environments/production.rb, config/environments/test.rb, docker-compose.yml, script/poll-for-db, test-envs/docker-compose-mysql.yml
Fixes #3066
Fixes #3065 
Decided to move the theme compilation stuff from under the asset group to the default group as suggested also in #3066. The rationale for the separate group would be to limit the amount of libraries in the production container; however it can be argued that the production container should also be able to build it's image. Additionally it seems that having it under a separate group would also require all asset precompilation to include the RAILS_GROUPS environment variable (as that also affects the gems required automatically in config/application.rb row `Bundler.require(*Rails.groups)`). So basically it seems like unnecessary hassle to have it separate, as having the extra code in the container isn't all that problematic, if not optimal either.
=> Upgrade to Rails 7.1 and add some environment fixes
