doc/installation.md

As requested following the db groups Gemfile update.

Update install doc to use db groups

---

config/locales/de.yml
config/locales/en.yml

Add missing translation

---

app/views/todos/add_predecessor.js.erb

replaceWith instead of html

---

app/models/project.rb
features/step_definitions/project_list_steps.rb
test/models/project_from_todo_test.rb
test/models/project_test.rb

(2.3) create projects as reviewed at creation time

---

app/controllers/todos_controller.rb

See #1834 for a discussion
Fixes #1834

(2.3) in tag view, do not use more-or-less random context for the form

---

app/helpers/todos_helper.rb
app/views/contexts/_context_form.html.erb
app/views/contexts/_new_context_form.html.erb
app/views/notes/_note_edit_form.html.erb
app/views/projects/_new_project_form.html.erb
app/views/projects/_project_form.html.erb
app/views/shared/_add_new_item_form.html.erb
app/views/todos/_edit_form.html.erb
app/views/todos/_edit_form.m.erb
app/views/todos/_new_multi_todo_form.html.erb
app/views/todos/_new_todo_form.html.erb
app/views/todos/edit.m.erb
app/views/todos/new.m.erb

(2.3) remove all tab indices

---

app/controllers/projects_controller.rb
app/controllers/recurring_todos_controller.rb

Show meaningful numbers in badge for completed projects and recurring actions

---

app/helpers/todos_helper.rb

Ignore time, so that one can always defer to the due date

---

app/controllers/notes_controller.rb
app/views/notes/destroy.js.erb

navigate back to note's project after deletion

---

app/helpers/todos_helper.rb

Show links to context/project also for completed actions

---

.travis.yml

as described in http://docs.travis-ci.com/user/caching/

enable caching of gems on travis

---

app/controllers/contexts_controller.rb
app/controllers/projects_controller.rb
app/controllers/stats_controller.rb
app/controllers/todos/todo_create_params_helper.rb
app/controllers/todos_controller.rb
app/helpers/projects_helper.rb
app/models/recurring_todos/abstract_recurrence_pattern.rb
app/models/stats/projects.rb
app/models/tag.rb
app/models/todo.rb
app/models/user.rb
lib/login_system.rb
lib/tracks/utils.rb
test/controllers/projects_controller_test.rb
test/models/context_test.rb
test/models/project_test.rb

The fasterer gem (https://github.com/DamirSvrtan/fasterer) suggest some speed improvements for Tracks. I've 'fixed' most of them,but left some that require more extensive refactoring.

speed improvements from fasterer gem

---

app/views/todos/_edit_form.html.erb
features/edit_a_todo.feature
features/step_definitions/todo_steps.rb

I think there's been a merge conflict in the last batch and this has been overridden. It's re-fixing a recent fix :)

Default project should be empty

---

app/models/user.rb
test/models/user_test.rb

Increase the maximum password length

---

app/models/recurring_todos/abstract_repeat_pattern.rb
test/models/recurring_todo_test.rb
test/models/recurring_todos/daily_repeat_pattern_test.rb

when recurring todos always use midnight for "show from"

---

config/initializers/assets.rb

It's no longer being included on its own anymore.
Fixes #1954

Remove the login stylesheet from precompilation

---

app/views/login/login.html.erb

fix: remember login

---

.dockerignore
Dockerfile

A first pass at an official Docker image based on [passenger-docker](https://github.com/phusion/passenger-docker). I have also registered the `tracksapp` org on Docker Hub.
Features:
* Ruby 2.2
* nginx + Passenger
* SQLite database
* site.yml and the database are stored in volumes at `/etc/tracks` and `/var/tracks`, respectively
* Database migrations are run on container startup so that manual intervention will rarely be needed during upgrades
Documentation to be added in a later PR.
Thanks to @staannoe for inspiring this.

Add Docker configuration

---

config/locales/es.yml

Updated Spanish translation

---

app/assets/javascripts/tracks.js.erb
app/assets/stylesheets/legacy.css.scss
app/assets/stylesheets/tracks.css.scss
app/helpers/preferences_helper.rb
app/views/preferences/_date_and_time.html.erb
app/views/preferences/_profile.html.erb
app/views/preferences/_tracks_behavior.html.erb
app/views/preferences/index.html.erb
app/views/users/_update_password.html.erb

No behavior changes, and all the features passed locally.

Update the preferences pages to Bootstrap

---

features/step_definitions/dependencies_steps.rb
features/step_definitions/todo_edit_steps.rb
features/step_definitions/todo_steps.rb
features/support/tracks_form_helper.rb
features/support/tracks_step_helper.rb

On Travis, before: 233 failures
After: still 233 failures... but trust me, this will come into its own once #1979 is addressed. :wink:
Locally, for example, this takes dependencies.feature from 10 failures to 0.

Address some Cucumber failures

---

app/controllers/users_controller.rb

Clean up reference to check_for_deprecated_password_hash

---

app/controllers/application_controller.rb
app/controllers/contexts_controller.rb
app/controllers/projects_controller.rb
app/controllers/search_controller.rb
app/controllers/todos_controller.rb
app/helpers/todos_helper.rb
app/models/project.rb
app/models/todo.rb
db/migrate/20160131233303_remove_project_hidden_state_from_todos.rb
test/controllers/contexts_controller_test.rb
test/controllers/projects_controller_test.rb
test/controllers/todos_controller_test.rb
test/models/todo_test.rb

I intend to clean this up a bit, but right now I'd love to get some feedback.
Fixes #1423
Fixes #1082

Remove project hidden state

---

db/schema.rb

Restores CI functionality -- see https://travis-ci.org/TracksApp/tracks/jobs/125564555

Update schema.rb with RemoveProjectHiddenStateFromTodos migration

---

app/assets/javascripts/tracks.js.erb
app/assets/stylesheets/legacy.css.scss

* Position the dialog below the navbar
* Make sure the edit form is placed inside `.legacy-ui` in the DOM

Fix recurring todo dialogs

---

app/controllers/todos_controller.rb

remove TODO from code, migrated to #2018

---

app/views/todos/index.atom.builder
app/views/todos/index.ics.erb
app/views/todos/index.rss.builder
test/controllers/todos_controller_test.rb
test/models/recurring_todo_test.rb
test/test_helper.rb

fixes #1726
the name @not_done_todos is wrong and should be replaced in a dedicated fix
**Note that this targets the 2.3 branch**

use @not_done_todos for feeds

---

app/helpers/application_helper.rb

bug introduced in c46e5a9e1d45f39f30464c16fb4c1606b1833ce7
fixes #2063

add missing space

---

app/helpers/rendering_helper.rb
test/controllers/todos_controller_test.rb
test/helpers/rendering_helper_test.rb

Move and refactor tests for `rendering_helper`

---

Gemfile.lock
app/views/recurring_todos/_recurring_todo.html.erb

reorder buttons for recurring todos to make the order uniform

---

app/assets/javascripts/tracks.js.erb
app/views/projects/update_project_name.js.erb

I moved the changes that I originally made on the jeditable plugin to the track.js.erb file.

A more rational way to load the text input with the previous names

---

app/views/layouts/application.html.erb
app/views/search/_index.html.erb
app/views/shared/_navbar.html.erb

Displays a search bar in the Navbar. Makes searching a lot easier and more convenient.

Feature search in navbar

---

Gemfile
app/controllers/contexts_controller.rb
app/controllers/todos_controller.rb
app/models/context.rb
app/models/project.rb
app/models/search/search_results.rb
config/boot.rb
db/schema.rb

Also update some other miscellaneous things from pieces of the upgrade

Remove deprecations announced in Rails 5.2

---

Dockerfile
Gemfile.lock

It seems to work with Rails just fine and doing this will stop the
fighting between my local non-docker environment and the docker
environment.

Upgrade to Bundler 2

---

app/controllers/contexts_controller.rb
app/controllers/projects_controller.rb
app/controllers/todos_controller.rb
lib/login_system.rb
test/controllers/projects_controller_test.rb

This allows using the token GET parameter with REST API requests also.

#2203: Allow using REST API with token

---

app/controllers/recurring_todos_controller.rb

Fixes #2094
Not all the cases in that issue where addressed, since a couple of them
were arrays and not queries.

Use exists? instead of count > 0

---

app/models/project.rb

Prefer !exists? over empty?

---

config/initializers/rack-mini-profiler.rb

Alternative to #2228.
It's far less in the way here. It's also hide-able with Alt-P (if you don't have a textbox focused.)

Move the profiler to the bottom left.

---

app/assets/javascripts/tracks.js.erb
app/controllers/todos_controller.rb
app/helpers/todos_helper.rb
app/views/contexts/_context.html.erb

make drag&drop todos from/to contexts work again  - fix #2054

---

app/assets/javascripts/tracks.js.erb
features/project_edit.feature

also update project name in multiple-actions mode

---

app/controllers/todos_controller.rb

#2249: Add space between sentences

---

db/migrate/20190618202817_add_user_id_to_tag.rb

replace " by '
use row['colname'] instead of row[n]
fixes #2277

Fix 2277: Adapt migration script for PostgreSQL

---

README.md
config/initializers/tracks.rb
doc/CHANGELOG.md
doc/upgrading.md

Version 2.4.0

---

README.md
config/initializers/tracks.rb
doc/CHANGELOG.md
doc/upgrading.md

A few security vulnerabilities have been addressed.
Pushing for more releases in 2020.

Prep for a v2.4.2 release

---

app/controllers/login_controller.rb

This should fix the errors with the periodic login expiration check that fails because we're trying to do math on a String.

Parse the session time so we can calculate expire time.

---

doc/upgrading.md

(I only added point no. 4, the rest of diff is just renumbering.)

doc: Mention Docker skip option

---

Dockerfile
README.md
config/database.docker.yml
config/site.docker.yml

Better Docker integration – this seems to work at least for me.

Better Docker integration

---

Gemfile
Gemfile.lock

Try upgrading just to v4 instead of the v5 Dependabot is suggesting in #2418 
Fixes #2401.

Update aasm to v4.

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/black.scss
app/assets/stylesheets/colors.scss
app/assets/stylesheets/legacy.scss
app/assets/stylesheets/light_blue.scss
app/assets/stylesheets/login.scss
app/assets/stylesheets/manifest.scss
app/assets/stylesheets/tracks.scss
app/controllers/application_controller.rb
app/controllers/login_controller.rb
app/controllers/preferences_controller.rb
app/helpers/application_helper.rb
app/models/preference.rb
app/views/layouts/application.html.erb
app/views/layouts/login.html.erb
app/views/preferences/_tracks_behavior.html.erb
config/initializers/assets.rb
config/locales/en.yml
config/site.yml.tmpl
db/migrate/20200820000743_add_theme_to_preference.rb
db/schema.rb
lib/common.rb

Fixes #2439.
This replaces the heavy black background of the menu, login screen and side form by a shade of blue.
Some pictures for comparison:
Any comments?

New colors to replace the heavy black.

---

.github/workflows/continuous-integration.yml
Dockerfile-2.5
Dockerfile-2.7
Gemfile
Gemfile.lock
app/controllers/todos_controller.rb
app/models/context.rb
app/models/note.rb
app/models/project.rb
app/models/search/search_results.rb
lib/common.rb
script/cibuild
test-envs/docker-compose-2.5-mysql.yml
test-envs/docker-compose-2.6-mysql.yml
test-envs/docker-compose-2.6-postgres.yml
test-envs/docker-compose-2.6-sqlite.yml
test-envs/docker-compose-2.7-mysql.yml
test/controllers/search_controller_test.rb
test/controllers/todos_controller_test.rb
test/models/user_test.rb

Run tests on all supported platforms

---

app/controllers/todos_controller.rb
test/controllers/todos_controller_test.rb

#2471: Adding todo fails in context view

---

app/controllers/todos_controller.rb
test/controllers/todos_controller_test.rb

#2472: Editing an due date from the calendar causes server error

---

README.md
app/views/integrations/help.html.erb

#2486: Change Gitter to Matrix

---

app/controllers/todos_controller.rb

Fix setting the due date in the calendar view. Reverts part of abad8c7.
TODO:
Fixes #2534.

#2534: Fix setting the due date in the calendar view.

---

test/controllers/todos_controller_test.rb
test/fixtures/preferences.yml

Relates to the problem in #2546.

Add testing for locales

---

app/assets/javascripts/application.js
app/helpers/application_helper.rb
test/controllers/todos_controller_test.rb

Fix the jquery-ui datepicker i18n files' asset compilation

---

app/assets/stylesheets/black.scss
app/assets/stylesheets/light_blue.scss

Fix autocomplete accessibility content overflow

---

app/views/integrations/rest_api.html.erb
app/views/users/index.html.erb
config/locales/en.yml
config/locales/fi.yml

Make REST help translatable; fix a few missing translations

---

bin/rails

Fix the bin/rails script to run Rails – copy-paste error.

---

Dockerfile

Use the script in bin/ for running the rails server in the Docker image.

---

config/database.yml.tmpl
doc/installation.md

Added info for using a PostgreSQL database to the doc and template file.

Add info for using PostgreSQL

---

app/assets/javascripts-jquery-ui/datepicker-zh-TW.js
config/initializers/assets.rb
config/locales/zh-TW.yml

- Add jQuery UI datepicker Traditional Chinese localization file
- Add complete zh-TW locale file with translations for all UI elements
- Configure asset precompilation for datepicker locale files

Add Traditional Chinese (Taiwan) localization support
